config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resources :departures, only: %i[post index] do
    post 'book', to: 'tickets#create'
  end

  root to: 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/departure.rb
class Departure < ApplicationRecord
  LATE_TIME_START = 22
  LATE_TIME_END = 6

  has_many :tickets

  validates :route, :departure_time, :arrival_time, :cost_in_cents, :seats_available, presence: true

  scope :available, -> { where('departure_time > ? and seats_available > 0', 2.hours.from_now) }

  def late
    local_time = arrival_time.localtime - arrival_time.localtime.at_beginning_of_day

    local_time >= LATE_TIME_START.hours || local_time <= LATE_TIME_END.hours
  end

  def cost_in_dollars
    format('%.2f', (cost_in_cents / 100.0))
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :departure
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickets

  validates :email, presence: true,
                    format: { with: URI::MailTo::EMAIL_REGEXP, message: 'must be a valid email address' }
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    else
      redirect_to sign_in_path
    end
  end

  def client_ip
    request.env['HTTP_X_FORWARDED_FOR'] || request.remote_ip
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @departures = Departure.available
                           .paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :set_current_user, only: %i[new create]
  def new
    @user = User.new
  end

  def create
    params[:user][:ip_address] = client_ip
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      set_current_user
      redirect_to root_path, notice: 'Registered successfully.'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :ip_address)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :set_current_user, only: %i[new create destroy]

  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user
      session[:user_id] = user.id
      set_current_user
      redirect_to root_path, notice: 'Signed in successfully.'
    else
      flash[:alert] = 'Incorrect email or password.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Successfully logged out.'
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def create
    params[:ip_address] = client_ip
    ticket = Current.user.tickets.new(ticket_params)
    if ticket.save
      redirect_to root_path, notice: 'Booked ticket successfully.'
    else
      flash[:alert] = 'Booking is failed. Please try again!'
      redirect_to root_path
    end
  end

  private

  def ticket_params
    params.permit(:departure_id, :ip_address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_time(datetime)
    datetime.strftime('%Y-%m-%d %H:%M')
  end
end

app/views/departures/_departure.html.erb
<tr class="<%= departure.late ? 'late' : '' %>">
  <th scope="row"><%= departure.route %></th>
  <td><%= format_time(departure.departure_time.localtime) %></td>
  <td><%= format_time(departure.arrival_time.localtime) %></td>
  <td><%= departure.cost_in_dollars %></td>
  <td><%= departure.seats_available %></td>
  <td><%= button_to 'Book', departure_book_path(departure.id),
      class: 'btn btn-primary btn-sm', data: { confirm: "Book the ticket now?" } %>
  </td>
</tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainBooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render partial: "shared/navbar" %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1>Train Timetable</h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Route</th>
          <th scope="col">Departure Time</th>
          <th scope="col">Arrival Time</th>
          <th scope="col">Cost</th>
          <th scope="col">Seats Available</th>
        </tr>
      </thead>
      <tbody>
        <%= render @departures %>
        <%= will_paginate @departures, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Train Booking</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <span class="navbar-text"><%= Current.user.email %></span>
          <li class="nav-item">
            <%= button_to 'Logout', logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', sign_in_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', sign_up_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>